version: "3"

services:
  backbone:
    build: ./services/backbone
    ports: 
      - "3030:3030"
    container_name: backbone
    volumes:
      - ./services/backbone:/app/backbone

  chatty-ui:
    build: ./services/chatty-ui
    ports:
      - "80:80"
    container_name: chatty-ui
    stdin_open: true
    volumes:
      - ./services/chatty-ui:/app/chatty-ui
